"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

files: [
 {
  "source" : "app.json",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "ios-infoPlist.json",
  "update_option" : "update_as_unapproved",
 }
]
