project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: 'app.json'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
    update_option: 'update_as_unapproved'
  - source: 'app.stringsdict'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
    update_option: 'update_as_unapproved'
  - source: 'ios-infoPlist.json'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
    update_option: 'update_as_unapproved'
